apiVersion: v1
kind: ReplicationController 
metadata:
      name: nginx-container
      labels:
         env: Demo
spec:
    template:
      metadata: 
        name: nginx-test
        labels:
           env: Demo 
      spec:
          containers:
          - name: nginx-container
            image: nginx
            ports:
            - containerPort: 80
    replicas: 3 
